Feature/jibreen model
AHL-Logics-backend-tranining-2024/Final-Project---Team-2 pull request #1
Opened 2024-09-27 22:01 UTC by JbreenJboor1212

### Summary:
In this branch, I created the User and Token models and implemented the /users/ endpoint to create a new user. This setup is essential as it lays the groundwork needed for creating tokens and implementing the login functionality in future updates.

### Key Changes:

- **User Model**: Defines user attributes including username, email, hashed_password, is_admin, is_active, created_at, and updated_at.

- **Token Model**: Establishes the structure for handling JWT tokens (access_token and token_type).
- **Create User Endpoint (POST /users/)**:
   - Validates the input fields for username, email, and password based on defined constraints.
   - Hashes the password securely using bcrypt.
   - Stores the user in a fake database (using a dictionary) with default values for is_admin and is_active.
   - Responds with user details, excluding the hashed password for security.

### Next Steps:
Use the created user data to generate tokens and implement login authentication endpoints.

2024-09-28 15:32 UTC, habeeb-misopex commented
approved

2024-09-29 14:08 UTC, Mohammed-samaheen commented
> approved

that is not how we approve, you should go to the file changes and then add your review

2024-09-29 14:33 UTC, Mohammed-samaheen requested changes

2024-09-29 14:33 UTC, Mohammed-samaheen commented on app/schemas/user.py
Schema generally refers to different things in the backend, so just keep the name as `model`.

2024-09-29 14:33 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +    PASSWORD_REGEX: ClassVar[str] = (
There is no need for this complexity you can add it like this
```
password: str = Field(
        ...,
        min_length=8,
        pattern=r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$',
    )
```

2024-09-29 14:33 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +    PASSWORD_REGEX: ClassVar[str] = (
Also I like to use UserCreateRequestModel instead of UserCreate

2024-09-29 14:33 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +    def to_dict(self):
we do not need this one we can use `model_dump` from the BaseModel

2024-09-29 14:33 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +class CreateUserResponseModel(BaseModel):
Instead of inheriting from BaseModel, use UserBaseModel.

2024-09-29 14:33 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +class UserBase(BaseModel):
UserBaseModel

2024-09-29 17:04 UTC, JbreenJboor1212 commented on app/schemas/user.py
I did it.

2024-09-29 17:05 UTC, JbreenJboor1212 commented on app/schemas/user.py
> +    PASSWORD_REGEX: ClassVar[str] = (
I used a different approach because the pattern is not supported in my version of Python.

2024-09-29 17:05 UTC, JbreenJboor1212 commented on app/schemas/user.py
> +    def to_dict(self):
I removed it

2024-09-29 17:06 UTC, JbreenJboor1212 commented on app/schemas/user.py
> +class CreateUserResponseModel(BaseModel):
Done

2024-09-29 17:06 UTC, JbreenJboor1212 commented on app/schemas/user.py
> +class UserBase(BaseModel):
Done

2024-09-30 05:07 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +class CreateUserResponseModel(BaseModel):
Are you still using BaseModel instead of UserBaseModel

2024-09-30 08:55 UTC, JbreenJboor1212 commented on app/schemas/user.py
> +class CreateUserResponseModel(BaseModel):
I implemented the change, but the return value is represented as
` {
  "username": "string",
  "email": "user@example.com",
  "id": "12b0d4ec-bc40-48f4-8ae6-9bb88f458eb0",
  "is_admin": false,
  "is_active": true,
  "created_at": "2024-09-30 08:34:26"
}`
not as 
`{
  "id": "12b0d4ec-bc40-48f4-8ae6-9bb88f458eb0",
  "username": "string",
  "email": "user@example.com",
  "is_admin": false,
  "is_active": true,
  "created_at": "2024-09-30 08:34:26"
}` 
 How can I solve this ?

2024-09-30 09:11 UTC, Mohammed-samaheen commented on app/schemas/user.py
> +class CreateUserResponseModel(BaseModel):
Not sure, but it's most likely a bug in pydintic. Anyway, it's in json format, and the order doesn't matter.

2024-09-30 09:12 UTC, Mohammed-samaheen approved these changes

2024-09-30 09:13 UTC, merged