Feature/jibreen order status
AHL-Logics-backend-tranining-2024/Final-Project---Team-2 pull request #3
Opened 2024-10-02 17:23 UTC by JbreenJboor1212

**The code defines CRUD endpoints for managing order statuses in FastAPI. It includes the following:**

- **Create Status `(POST /)`**: Adds a new order status if the name does not already exist, returning the created status.
- **Get Status by ID `(GET /{status_id})`**: Retrieves the order status by its unique ID, returning a 404 error if not found.
- **Update Status `(PUT /{status_id})`**: Updates the name of an existing status if the new name is unique, otherwise returns a conflict error.
- **Delete Status `(DELETE /{status_id})`**: Deletes an order status if it is not linked to any existing orders, otherwise prevents deletion.

All endpoints ensure that only an authenticated admin user can access or modify the statuses, using proper error handling to catch potential issues.

2024-10-02 20:41 UTC, habeeb-misopex approved these changes

2024-10-03 08:01 UTC, Mohammed-samaheen requested changes

2024-10-03 08:01 UTC, Mohammed-samaheen commented on app/models.py
> +class OrderStatusCreateModel(OrderStatusBaseModel):
please follow this convention of naming models 
[method][model type][request tupe]Model
so this should be
CreateOrderStatusRequestModel

2024-10-03 08:01 UTC, Mohammed-samaheen commented on app/api/routes/status.py
> +        updated_at=datetime.now(timezone.utc)
update date for created status?

2024-10-03 08:01 UTC, Mohammed-samaheen commented on app/models.py
> +class DeleteResponseModel(BaseModel):
Please make sure to follow the task description. In delete, we return nothing.

2024-10-03 08:01 UTC, Mohammed-samaheen commented on app/models.py
> +class OrderStatusResponseModel(OrderStatusModel):
create doesn't have updated_at

2024-10-03 08:19 UTC, JbreenJboor1212 commented on app/models.py
> +class OrderStatusCreateModel(OrderStatusBaseModel):
I forgot about that, I'll refactor it now.

2024-10-03 08:22 UTC, JbreenJboor1212 commented on app/api/routes/status.py
> +        updated_at=datetime.now(timezone.utc)
I think when creating the first one, the same will be updated. But if it doesn't work, I'll return null.

2024-10-03 08:22 UTC, JbreenJboor1212 commented on app/models.py
> +class DeleteResponseModel(BaseModel):
I think when creating the first one, the same will be updated. But if it doesn't work, I'll return null.

2024-10-03 08:38 UTC, JbreenJboor1212 commented on app/models.py
> +class OrderStatusCreateModel(OrderStatusBaseModel):
Done. Your idea is better than mine. Thanks!

2024-10-03 08:38 UTC, JbreenJboor1212 commented on app/api/routes/status.py
> +        updated_at=datetime.now(timezone.utc)
Done. Your idea is better than mine. Thanks!

2024-10-03 08:38 UTC, JbreenJboor1212 commented on app/models.py
> +class DeleteResponseModel(BaseModel):
Done. Your idea is better than mine. Thanks!

2024-10-03 08:38 UTC, JbreenJboor1212 commented on app/models.py
> +class OrderStatusResponseModel(OrderStatusModel):
Done. Your idea is better than mine. Thanks!

2024-10-03 08:40 UTC, JbreenJboor1212 commented on app/models.py
> +class OrderStatusResponseModel(OrderStatusModel):
@Mohammed-samaheen Please review my changes.

2024-10-03 08:57 UTC, Mohammed-samaheen approved these changes

2024-10-03 08:58 UTC, merged