Feature/jibreen products endpoints
AHL-Logics-backend-tranining-2024/Final-Project---Team-2 pull request #6
Opened 2024-10-07 09:36 UTC by JbreenJboor1212

### Product Management Endpoints

This module introduces CRUD (Create, Read, Update, Delete) endpoints for managing products in the e-commerce API. The implementation includes robust validation, error handling, and flexible search functionality.

#### Endpoints

#### 1. Create Product (`POST /`)
- Allows authorized admin users to create a new product.
- Ensures product names are unique.
- Returns product details, including `id`, `name`, `price`, `description`, `stock`, `isAvailable`, and `created_at`.

#### 2. Update Product (`PUT /{product_id}`)
- Allows authorized admin users to update a product by its UUID.
- Only updates the fields provided, leaving others unchanged.
- Ensures product name uniqueness during updates.
- Automatically updates the `updated_at` timestamp.

#### 3. Delete Product (`DELETE /{product_id}`)
- Allows authorized admin users to delete a product by its UUID.
- Returns `204 No Content` upon successful deletion.
- Raises an error if the product is not found.

#### 4. Get All Products (`GET /`)
- Retrieves a list of all available products, returning key information for each product.
- Returns an empty list if no products are available.

#### 5. Search Products (`GET /search`)
- Enables product search with flexible filters such as `name`, `min_price`, `max_price`, and `isAvailable` status.
- Supports sorting by `price` or `name`, with ascending or descending order.
- Includes pagination to manage large result sets.

#### 6. Get Product by ID (`GET /{product_id}`)
- Fetches detailed information about a specific product by its UUID.
- Provides product details such as `id`, `name`, `price`, `stock`, and timestamps.

### Validation and Error Handling
- Comprehensive validation for request inputs and proper error messages for various scenarios (e.g., duplicate product name, invalid UUID format).
- Uses appropriate HTTP status codes to signal success (`201 Created`, `200 OK`, `204 No Content`) and error conditions (`400 Bad Request`, `404 Not Found`).

2024-10-07 09:39 UTC, Habeeb-Awawda approved these changes

2024-10-08 15:51 UTC, Mohammed-samaheen requested changes

2024-10-08 15:51 UTC, Mohammed-samaheen commented on app/models.py
> +    created_at: datetime
ProductBaseModel doesn't have an id

2024-10-08 15:51 UTC, Mohammed-samaheen commented on app/api/routes/product.py
> +        raise HTTPException(status_code=400, detail="Product ID must be a valid UUID.")
no need for this one

2024-10-08 16:18 UTC, JbreenJboor1212 commented on app/api/routes/product.py
> +        raise HTTPException(status_code=400, detail="Product ID must be a valid UUID.")
Done

2024-10-08 16:22 UTC, JbreenJboor1212 commented on app/models.py
> +    created_at: datetime
Done .

2024-10-08 16:29 UTC, JbreenJboor1212 commented on app/api/routes/product.py
> +        raise HTTPException(status_code=400, detail="Product ID must be a valid UUID.")
Thank you for your feedback. I have a clearer perspective now and I'm working on avoiding the simple mistakes I made before and learning from them. The revisions have decreased, and the day errors were just due to lack of focus. I'll improve over time. @Mohammed-samaheen

2024-10-08 16:53 UTC, Mohammed-samaheen approved these changes

2024-10-08 16:58 UTC, merged