Feature/setup db
AHL-Logics-backend-tranining-2024/Final-Project---Team-2 pull request #9
Opened 2024-10-12 12:10 UTC by JbreenJboor1212

**Set up the database implementation.**

2024-10-12 12:11 UTC, habeeb-misopex approved these changes

2024-10-13 05:33 UTC, Mohammed-samaheen requested changes

2024-10-13 05:33 UTC, Mohammed-samaheen commented on app/connection_to_db.py
> +SQLALCHEMY_DATABASE_URL = "postgresql://admin:adminpass@db:5432/fastapi_db"
this should be an environment variable

2024-10-13 07:30 UTC, JbreenJboor1212 commented on app/connection_to_db.py
> +SQLALCHEMY_DATABASE_URL = "postgresql://admin:adminpass@db:5432/fastapi_db"
Done

2024-10-13 07:39 UTC, Mohammed-samaheen approved these changes

2024-10-13 07:44 UTC, merged